CREATE DATABASE Parti;

USE Parti;

CREATE TABLE  Login (
	cod INT(8) NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	username VARCHAR(15) NOT NULL UNIQUE, 
	email VARCHAR(20) NOT NULL UNIQUE,
	password VARCHAR(10) NOT NULL
);

CREATE TABLE  User (
	id INT(8) NOT NULL PRIMARY KEY,
	first_name VARCHAR(15) DEFAULT NULL, 
	last_name VARCHAR(20) DEFAULT NULL,
	age INT DEFAULT NULL, 
	city VARCHAR(15) DEFAULT NULL, 
	
	FOREIGN KEY(id)
	REFERENCES Login(cod)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);


CREATE TABLE  Location (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(40) NOT NULL,
	description VARCHAR(255) DEFAULT NULL,
	address VARCHAR(25) NOT NULL, 
	city VARCHAR(25) NOT NULL, 
	zipcode INT(20) NOT NULL 
);

CREATE TABLE  Event (
	cod INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(15) NOT NULL, 
	description VARCHAR(255) DEFAULT NULL,
	datetime_start DATETIME NOT NULL, 
	datetime_end DATETIME NOT NULL, 
	location INT(20) NOT NULL,

	FOREIGN KEY(location)
	REFERENCES Location(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

CREATE TABLE  Offers (
	cod INT NOT NULL PRIMARY KEY,
	user INT(8) NOT NULL, 
	event INT NOT NULL,
	price INT DEFAULT NULL, 
	city VARCHAR(15) NOT NULL,
	seats INT DEFAULT 1,

	FOREIGN KEY(user)
	REFERENCES User(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,

	FOREIGN KEY(event)
	REFERENCES Event(cod)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

CREATE TABLE  Ratings (
	author INT NOT NULL, 
	receiver INT NOT NULL,
	description VARCHAR(400) DEFAULT NULL,
	creation DATETIME DEFAULT CURRENT_TIMESTAMP, 
	event INT NOT NULL, 
	rating INT NOT NULL,

	PRIMARY KEY (author,receiver,event),

	FOREIGN KEY(author)
	REFERENCES User(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,

	FOREIGN KEY(receiver)
	REFERENCES User(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,

	FOREIGN KEY(event)
	REFERENCES Event(cod)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

